### ISSUE TITLE
[configuration] Development Environment

### ISSUE THREAD

**Issue by rg00dwin** [jpfxgood/ped#1]
Do you ever use vscode  for running the tests?  Or do you just run `python -m pytest tests`

n.m. - I figured out how to run the tests in vscode.. They wouldn't run because imports were failing - couldn't find the modules. Had to add a '.env' file that set  PYTHONPATH environment variable correctly.. Works now. the tests can be run now with the
vscode  'Debug all test' selection.. 

Sorry for the spam..

**Comment by jpfxgood** [comment]
I got around it by creating my own configurations for running the editor either directly or running pytest.
You can just pop in the -k argument as needed to only run one test function, saves a lot of time...
This is what my "launch.json" file looks like:
`{
    // Use IntelliSense to learn about possible attributes.    
    // Hover to view descriptions of existing attributes.    
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "ped",
            "args": ["/home/james/ped-git/editor_common.py"],
            "console": "externalTerminal"
        },
        {
            "name": "Python: Pytest",
            "type": "python",
            "request": "launch",
            "module": "pytest",
            "args": [ "tests", "-k", "test_EditorManager" ],
            "env" : { "SSH_DIALOG_BASEPATH":"ssh://james-server/home/james", "SSH_DIALOG_USERNAME":"james", "SSH_DIALOG_PASSWORD":"************" },
            "console": "externalTerminal"
        }
    ]
}`

**Comment by rg00dwin** [comment]
Thanks - I also like the way you've included the environment VARs SSH_DIALOG* into the launch.json... I've been setting them every time I bring up vscode and was just about to put them in the .env file when I saw your comment.

**Comment by rg00dwin** [comment]
Got the sftp bit of the dialog test to run:
`DEBUG    paramiko.transport.sftp:sftp.py:158 [chan 6] rmdir(b'/tmp/tmp/pytest-of-roy/pytest-30')
DEBUG    paramiko.transport.sftp:sftp.py:158 [chan 6] rmdir(b'/tmp/tmp/pytest-of-roy')
INFO     paramiko.transport.sftp:sftp.py:158 [chan 6] sftp session closed.
DEBUG    paramiko.transport:channel.py:1212 [chan 6] EOF sent (6)
DEBUG    paramiko.transport:channel.py:1212 [chan 6] EOF received (6)
===================================== short test summary info ======================================
FAILED tests/test_dialog.py::test_dialog - OverflowError: byte doesn't fit in chtype
FAILED tests/test_editor_common.py::test_Editor_unwrapped - OverflowError: byte doesn't fit in ch...
FAILED tests/test_editor_common.py::test_Editor_wrapped - AssertionError
FAILED tests/test_editor_manager.py::test_EditorFrame - OverflowError: byte doesn't fit in chtype
FAILED tests/test_editor_manager.py::test_EditorManager - OverflowError: byte doesn't fit in chtype
FAILED tests/test_ssh_dialog.py::test_ssh_dialog - OverflowError: byte doesn't fit in chtype
============================= 6 failed, 7 passed in 138.41s (0:02:18) ==============================`

Before - I was getting an ERROR: Permission denied on the local sftp server I had running.. 

I think it was due to me specifying SSH_DIALOG_BASEPATH as 'SSH_DIALOG_BASEPATH=ssh://bigboy/tmp:21' as indicated in the README.md, but then I looked at your launch.json and you omitted the port number.. Once I did that - it ran to completion 

got the above results running an a terminal 'python -m pytest tests'

I've somehow broken the ability to run the tests from w/in vscode as most tests now fail with:

```
test_c_mode: test_c_mode
Fail: _curses.error: nocbreak() returned ERRpytest(./tests/test_c_mode.py::test_c_mode)
test_c_mode.py(8, 5): test_c_mode
__init__.py(89, 9): cbreak()
test_c_mode.py(73, 9): curses.wrapper(main)
__init__.py(111, 13): nocbreak()
Peek Problem (Alt+F8)
```
hah - I never touched nocbreak or curses  - I probably bumped some delicate bit of vscode setting.. :smiley:

**Comment by jpfxgood** [comment]
Yeah I got that too and so that's why I switched to the externalTerminal setting, the embedded terminal is messing with curses somehow and I prefer a separate window anyway... I didn't have the motivation to run down the problem in vscode...

**Comment by rg00dwin** [comment]
AH! That's really good to know.  I thought I had done something bad to vscode... OK  - I will switch to externalTeminal setting. REALLY good to know.. hah.. there's just a lot of rumors out there on the web about the nocbreak error..
