### ISSUE TITLE
Feature request - marking text with mouse

### ISSUE THREAD

**Issue by rg00dwin** [jpfxgood/ped#16]
When marking text with the mouse (left click & drag) the area of text to be marked does not get highlighted until the left mouse button is released. I  would find it helpful if the marked area highlighting was updated while I was dragging..

**Comment by jpfxgood** [comment]
Yes, I need to do this... I'll have a look soon...

**Comment by jpfxgood** [comment]
sigh, I just went down this road again... I remember now why I didn't do it before... on most terminals curses doesn't get mouse move events so there isn't anything in the queue while the mouse is down and moving... There are apparently changes that can be made to terminfo to make it work, I tried the most credible one I could find: https://stackoverflow.com/questions/29020638/which-term-to-use-to-have-both-256-colors-and-mouse-move-events-in-python-curse
And it didn't do anything interesting... I think it's just gonna have to be the way it is...

**Comment by rg00dwin** [comment]
![image](https://user-images.githubusercontent.com/18055220/86627087-b53e1b00-bf95-11ea-9a9f-a6fe1801a43a.png)
